.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bitcoinrandom_qt test_bitcoinrandom_qt
clean: FORCE
	$(MAKE) -C .. bitcoinrandom_qt_clean test_bitcoinrandom_qt_clean
check: FORCE
	$(MAKE) -C .. test_bitcoinrandom_qt_check
bitcoinrandom-qt bitcoinrandom-qt.exe: FORCE
	 $(MAKE) -C .. bitcoinrandom_qt
